rvm: '2.3.0'
before_install:
  - gem install bundler bundle_cache
  - bundle_cache_install
script: bundle exec rspec spec
script:
  - bundle exec bin/rake db:create
  - bundle exec bin/rake db:migrate
  - bundle exec rspec spec
